# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5                       # Number of pages displayed in pagination
    default_options:
        page_name: page                  # Parameter name for the page in the URL
        sort_field_name: sort            # Parameter name for the sorting field in the URL
        sort_direction_name: direction   # Parameter name for the sorting direction in the URL
        filter_field_name: filterField   # Parameter name for the filtering field
        filter_value_name: filterValue   # Parameter name for the filtering value
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Custom template (e.g., for Bootstrap 5)
