liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        
        thumbnail:
            quality: 100
            filters:
                thumbnail:
                    size: [300, 250]
                    mode: outbound
                    
        thumbnail_tour_view:
            quality: 100
            filters:
                thumbnail:
                    size: [300, 200]
                    mode: outbound

        thumbnail_get_into_bhutan_air:
            quality: 100
            filters:
                thumbnail:
                    size: [500, 550]
                    mode: outbound      

        thumbnail_get_into_bhutan_road:
            quality: 100
            filters:
                thumbnail:
                    size: [500, 600]
                    mode: outbound              

        thumbnail_admin_tour:
            quality: 100
            filters:
                thumbnail:
                    size: [500, 300]
                    mode: outbound                               
